CREATE TABLE majors (
    id       BIGSERIAL    PRIMARY KEY,
    name_ko  VARCHAR(100) NOT NULL UNIQUE,
    name_en  VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(50)  NOT NULL
);

INSERT INTO majors (name_ko, name_en, category) VALUES
-- 이공계
('컴퓨터공학',   'Computer Science & Engineering', '이공계'),
('소프트웨어공학', 'Software Engineering',           '이공계'),
('정보보안',     'Information Security',            '이공계'),
('인공지능',     'Artificial Intelligence',         '이공계'),
('데이터사이언스', 'Data Science',                   '이공계'),
('전기공학',     'Electrical Engineering',          '이공계'),
('전자공학',     'Electronic Engineering',          '이공계'),
('통신공학',     'Communications Engineering',      '이공계'),
('기계공학',     'Mechanical Engineering',          '이공계'),
('항공우주공학', 'Aerospace Engineering',            '이공계'),
('로봇공학',     'Robotics Engineering',            '이공계'),
('화학공학',     'Chemical Engineering',            '이공계'),
('재료공학',     'Materials Engineering',           '이공계'),
('에너지공학',   'Energy Engineering',              '이공계'),
('토목공학',     'Civil Engineering',               '이공계'),
('건축공학',     'Architectural Engineering',       '이공계'),
('환경공학',     'Environmental Engineering',       '이공계'),
('수학',         'Mathematics',                    '이공계'),
('통계학',       'Statistics',                     '이공계'),
('물리학',       'Physics',                        '이공계'),
('화학',         'Chemistry',                      '이공계'),
('생물학',       'Biology',                        '이공계'),
('지구과학',     'Earth Science',                  '이공계'),
-- 의약계
('의학',         'Medicine',                       '의약계'),
('치의학',       'Dentistry',                      '의약계'),
('한의학',       'Korean Medicine',                '의약계'),
('간호학',       'Nursing',                        '의약계'),
('약학',         'Pharmacy',                       '의약계'),
('수의학',       'Veterinary Medicine',            '의약계'),
('보건학',       'Public Health',                  '의약계'),
('물리치료학',   'Physical Therapy',               '의약계'),
('작업치료학',   'Occupational Therapy',           '의약계'),
-- 사회계
('사회학',       'Sociology',                      '사회계'),
('심리학',       'Psychology',                     '사회계'),
('정치학',       'Political Science',              '사회계'),
('행정학',       'Public Administration',          '사회계'),
('사회복지학',   'Social Welfare',                 '사회계'),
('법학',         'Law',                            '사회계'),
('언론정보학',   'Media & Communication',          '사회계'),
-- 인문계
('국어국문학',   'Korean Language & Literature',   '인문계'),
('영어영문학',   'English Language & Literature',  '인문계'),
('중어중문학',   'Chinese Language & Literature',  '인문계'),
('일어일문학',   'Japanese Language & Literature', '인문계'),
('독어독문학',   'German Language & Literature',   '인문계'),
('불어불문학',   'French Language & Literature',   '인문계'),
('역사학',       'History',                        '인문계'),
('철학',         'Philosophy',                     '인문계'),
('문화인류학',   'Cultural Anthropology',          '인문계'),
-- 예체능계
('미술학',       'Fine Arts',                      '예체능계'),
('시각디자인',   'Visual Design',                  '예체능계'),
('산업디자인',   'Industrial Design',              '예체능계'),
('패션디자인',   'Fashion Design',                 '예체능계'),
('음악학',       'Music',                          '예체능계'),
('연극영화학',   'Theatre & Film',                 '예체능계'),
('무용학',       'Dance',                          '예체능계'),
('체육학',       'Physical Education',             '예체능계'),
('스포츠과학',   'Sports Science',                 '예체능계'),
-- 사범계
('교육학',       'Education',                      '사범계'),
('유아교육학',   'Early Childhood Education',      '사범계'),
('초등교육학',   'Elementary Education',           '사범계'),
('특수교육학',   'Special Education',              '사범계'),
-- 경상계
('경영학',       'Business Administration',        '경상계'),
('경제학',       'Economics',                      '경상계'),
('회계학',       'Accounting',                     '경상계'),
('무역학',       'International Trade',            '경상계'),
('금융학',       'Finance',                        '경상계'),
('관광학',       'Tourism & Hospitality',          '경상계');
